name: 'slack-send-today-commits'
description: 'Publish a message in a channel with today commits'
inputs:
  channel-id: # channel id to post message when using bot token
    description: 'Slack channel ID where message will be posted. Needed if using bot token'
    required: false
  slack-message: # message to post when using bot token
    description: 'Message to post into Slack. Needed if using bot token'
    required: false
outputs:
  channel_id: # Id of the channel. If channel name was used as input we can get ID from output for later use when updating message or posting to thread.
    description: 'The channel id of the message that was posted into Slack when using bot token'
runs:
  using: 'node20'
  main: 'dist/index.js'
